from __future__ import annotations

import logging
import re
import time
import traceback
from functools import partial
from typing import TYPE_CHECKING, Any, Callable, Optional

from self_edit_env import SelfEditEnv
from round_validity import invalid_reason

if TYPE_CHECKING:
    from minisgl.llm import AsyncLLM
    from minisgl.shared_cache.shared_block import CacheBlock

logger = logging.getLogger(__name__)

HookFn = Callable[..., None]

FATAL_NOTE = """
Your current engine.py does not even compile/construct -- it is completely broken, so this \
thought is being generated by a fixed fallback path instead of your own `generate` method. Call \
`write_engine` with a fixed version and then `reload_engine_methods` to bring yourself back to \
life. The failure was:
"""

STUCK_NOTE = """
Your last round's completion came out byte-for-byte identical to the round before it -- you are \
stuck reproducing the same content instead of reasoning fresh (seen live: a persistent cache block \
kept alive across every call to `generate`, including the once-per-episode calls `act` makes during \
`start_task`/`restart_task`, can grow large enough that continuing from it just regurgitates \
whatever is already sitting inside it). This round is being generated by the safe fallback path \
instead of your own `generate` so you have a clean context to look at and decide what to do. If \
`engine.py` holds a persistent block on `self` that is never freed, its unbounded growth across \
*all* of those calls -- not just successive rounds of you rewriting yourself -- is the first thing \
worth checking.
"""

FALLBACK_PROMPT = """You are an inference engine that thinks by executing the Python code in \
`mutable/engine.py` and is instructed by `mutable/prompt.py`. Your `prompt.py` currently fails \
to compile/construct, or its `Prompting` instance has no string `system_prompt` attribute, so \
this minimal fallback is being used instead of your real instructions.

Call `write_prompt` with a fixed `prompt.py` (it must define a top-level class `Prompting` with \
`def __init__(self, llm)` that sets `self.system_prompt = "..."`) and then `reload_prompt` to \
restore your real instructions. Use this exact syntax:

<use_tool name="write_prompt">
```python
class Prompting:
    def __init__(self, llm):
        self.llm = llm
        self.system_prompt = \"\"\"<the full new prompt text>\"\"\"
```
</use_tool>
<use_tool name="reload_prompt"></use_tool>

The failure was:
"""

_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL)
_UNCLOSED_THINK_RE = re.compile(r"<think>.*", re.DOTALL)
_TOOL_CALL_RE = re.compile(r'<use_tool\s+name="(\w+)"\s*>(.*?)</use_tool>', re.DOTALL)

# Present only if decoding ran past the turn boundary into leaked context
# (e.g. an eos_token_id mismatch) -- cut before tool-call parsing so leaked
# text can't be mistaken for real <use_tool> calls.
_RUNAWAY_MARKERS = ("<|endoftext|>", "<|im_start|>")


def truncate_runaway(text: str) -> str:
    cut = min((text.find(m) for m in _RUNAWAY_MARKERS if m in text), default=len(text))
    return text[:cut]


def eos_ids(llm: "AsyncLLM") -> set[int]:
    """Union tokenizer.eos_token_id with generation_config.eos_token_id --
    the latter can list several ids the former misses, letting decoding run
    away if only one is checked."""
    ids = {llm.tokenizer.eos_token_id}
    gen_cfg = getattr(llm.config, "generation_config", None)
    gen_eos = getattr(gen_cfg, "eos_token_id", None)
    if isinstance(gen_eos, int):
        ids.add(gen_eos)
    elif isinstance(gen_eos, (list, tuple, set)):
        ids.update(gen_eos)
    return ids


def strip_think(text: str) -> str:
    text = _THINK_RE.sub("", text)
    text = _UNCLOSED_THINK_RE.sub("", text)
    return text


def extract_code(text: str) -> Optional[str]:
    if "```python" in text:
        return text.split("```python", 1)[1].split("```", 1)[0].strip()
    if "```" in text:
        return text.split("```", 1)[1].split("```", 1)[0].strip()
    return None


def build_env_turn(
    last_result: Optional[dict[str, Any]], task_status: Optional[str] = None,
    max_new_tokens: Optional[int] = None, best_so_far: Optional[tuple[float, int]] = None,
) -> str:
    """The last-round-outcome part of a round's prompt (tool results, crash
    text, task score/status), with no engine.py source dump or system-prompt
    preamble. Doubles as the compact per-round delta fed into a *reused*
    bootstrap_generate history block (see HistoryBlockState), since that
    block's real KV already holds the model's prior reasoning."""
    parts = []
    if last_result is not None:
        if last_result.get("fatal"):
            parts.append(FATAL_NOTE + last_result["error"])
        elif last_result.get("crash"):
            parts.append("\nYour last generation crashed before any tool calls could run:\n"
                          + last_result["crash"])
        else:
            tool_results = last_result.get("tool_results") or []
            if not tool_results:
                if last_result.get("near_budget"):
                    parts.append(
                        "\nYour last round used almost its entire token budget on reasoning text "
                        "and never completed a single <use_tool> call -- nothing changed, and no "
                        "result was recorded. Don't rehash your whole design from scratch in "
                        "reasoning before acting: state a short plan in a few sentences, then get "
                        "to <use_tool> calls quickly. If you're mid-rewrite, split the work across "
                        "rounds (write and apply an incremental change now) rather than trying to "
                        "think through a whole redesign before ever touching a tool call.")
                else:
                    parts.append("\nYour last round made no <use_tool> calls -- nothing changed.")
            else:
                lines = []
                for r in tool_results:
                    status = "OK" if r.get("ok") else "ERROR"
                    line = f"- {r.get('tool')}: {status}"
                    if not r.get("ok"):
                        line += f"\n  {r.get('error')}"
                    elif r.get("changed"):
                        line += f" (changed: {', '.join(r['changed'])})"
                    lines.append(line)
                parts.append("\nYour last round's tool calls:\n" + "\n".join(lines))
        if last_result.get("repeated"):
            parts.append(STUCK_NOTE)
        task = last_result.get("task")
        if task is not None:
            parts.append(f"\nLatest task score on `{task['env']}`: avg_reward={task['avg_reward']:.3f} "
                          f"over {len(task['episodes'])} episode(s).")
            # Bare avg_reward has no memory -- without this, a regression
            # looks like ordinary exploration noise. best_so_far tracks the
            # best score across the whole run (see run_step's on_result).
            if best_so_far is not None:
                best_score, best_round = best_so_far
                if task["avg_reward"] >= best_score:
                    parts.append(
                        f"This ties or beats your best score so far this run "
                        f"({best_score:.3f}, first reached at round {best_round}).")
                else:
                    parts.append(
                        f"Your best score so far this run is {best_score:.3f}, reached at round "
                        f"{best_round} -- this round's {task['avg_reward']:.3f} is a regression from "
                        "that. Some regression while experimenting is normal, but don't keep "
                        "building on a change that made things worse just because it's the most "
                        "recent one: if you can't tell why this round is behind, it's a legitimate "
                        "move to revert engine.py back toward whatever version scored "
                        f"{best_score:.3f} (you have it in your own context from round {best_round}) "
                        "rather than continuing to iterate away from it.")
            # A crashed episode (tasks/runner.py's per-episode try/except)
            # scores 0 with its traceback in episode info -- surface the
            # first one so a flat 0.0 isn't silent.
            error = next(
                (e["info"]["error"] for e in task["episodes"]
                 if isinstance(e.get("info"), dict) and e["info"].get("error")), None)
            if error:
                parts.append(
                    "An episode failed with this traceback -- fix whatever it points to in "
                    f"engine.py:\n{error}")
            # Mean per-episode avg_act_latency_s (tasks/doom_env.py) into one figure.
            latencies = [
                e["info"]["avg_act_latency_s"] for e in task["episodes"]
                if isinstance(e.get("info"), dict) and e["info"].get("avg_act_latency_s") is not None
            ]
            if latencies:
                avg_ms = sum(latencies) / len(latencies) * 1000
                line = (
                    f"Avg act() latency this task run: {avg_ms:.0f}ms "
                    "(mean wall-clock time between receiving an observation and returning an action).")
                if avg_ms < 50:
                    line += (
                        " This is far faster than any real forward pass -- it almost certainly means "
                        "act() is returning from a scripted/hardcoded fallback path instead of actually "
                        "calling the LLM every step (e.g. a failure counter that permanently disables "
                        "the real call after a few caught exceptions). Find and remove whatever is "
                        "short-circuiting the LLM call.")
                parts.append(line)
            calls = task.get("llm_forward_calls")
            steps = task.get("episode_steps_total")
            if calls is not None and steps:
                ratio = calls / steps
                line = (
                    f"This task run made {steps} env step(s) but the LLM was actually invoked "
                    f"(a real forward pass through `llm(...)`/`llm.forward(...)`) only {calls} "
                    f"time(s) in that same window ({ratio:.2f} forward passes per step).")
                if ratio < 0.1:
                    line += (
                        " This experiment is about designing an LLM-driven inference structure, "
                        "not about maximizing reward by any means -- a policy that mostly or "
                        "entirely avoids calling the LLM (e.g. falling back to a scripted/"
                        "heuristic action-selector because it happens to score comparably) is not "
                        "a valid result here even if the score above looks fine, and will not be "
                        "reported as a success. Find whatever in act() is routing around the real "
                        "LLM call and fix that before anything else.")
                parts.append(line)
    if task_status is not None:
        parts.append("\n" + task_status)
    if max_new_tokens is not None:
        parts.append(f"\nThis round's generation is capped at max_new_tokens={max_new_tokens}.")
    parts.append("\nWrite your next round (thinking, then <use_tool> calls):")
    return "\n".join(parts)


def build_prompt(
    source: str, last_result: Optional[dict[str, Any]], prompt: str,
    task_status: Optional[str] = None, max_new_tokens: Optional[int] = None,
    best_so_far: Optional[tuple[float, int]] = None,
) -> str:
    parts = [prompt, "\nCurrent engine.py:\n```python\n" + source + "\n```",
              build_env_turn(last_result, task_status, max_new_tokens, best_so_far)]
    return "\n".join(parts)


# Hard ceilings on tool-call execution per round (harness-only, not
# agent-editable). Seen live: a degenerate completion can repeat the same
# <use_tool> tag hundreds of times -- capping execution bounds the GPU
# damage from actually running each one (start_task/restart_task = full
# episodes).
MAX_TOOL_CALLS_PER_ROUND = 8
MAX_CONSECUTIVE_IDENTICAL_CALLS = 3


async def apply_tool_calls(
    env: SelfEditEnv, completion: str, on_result: Optional[HookFn] = None,
) -> list[dict[str, Any]]:
    """`on_result`, if given, fires as each tool call finishes rather than
    once at round end -- so a slow call (e.g. start_task) doesn't leave the
    structured logs looking stalled while main.log keeps moving."""
    text = strip_think(completion)
    results: list[dict[str, Any]] = []
    prev_call: Optional[tuple[str, str]] = None
    consecutive = 0

    def emit(result: dict[str, Any]) -> None:
        results.append(result)
        if on_result is not None:
            on_result(result)

    for name, inner in _TOOL_CALL_RE.findall(text):
        if len(results) >= MAX_TOOL_CALLS_PER_ROUND:
            emit({"tool": name, "ok": False,
                  "error": f"round tool-call budget exceeded ({MAX_TOOL_CALLS_PER_ROUND} max "
                           "calls per round) -- remaining calls in this round were skipped"})
            break
        call = (name, inner)
        consecutive = consecutive + 1 if call == prev_call else 1
        prev_call = call
        if consecutive > MAX_CONSECUTIVE_IDENTICAL_CALLS:
            emit({"tool": name, "ok": False,
                  "error": f"stopped after {MAX_CONSECUTIVE_IDENTICAL_CALLS} identical "
                           f"consecutive calls to {name!r} -- this looks like a generation "
                           "loop, not deliberate repetition; remaining calls in this round "
                           "were skipped"})
            break
        if name == "write_engine":
            source = extract_code(inner)
            if source is None:
                emit({"tool": name, "ok": False,
                      "error": "no code block found inside write_engine call"})
                continue
            emit({"tool": name, **env.write_engine(source)})
        elif name == "reload_engine_methods":
            emit({"tool": name, **env.reload_engine_methods()})
        elif name == "write_prompt":
            source = extract_code(inner)
            if source is None:
                emit({"tool": name, "ok": False,
                      "error": "no code block found inside write_prompt call"})
                continue
            emit({"tool": name, **env.write_prompt(source)})
        elif name == "reload_prompt":
            emit({"tool": name, **env.reload_prompt()})
        elif name == "start_task":
            emit({"tool": name, **await env.start_task()})
        elif name == "restart_task":
            emit({"tool": name, **await env.restart_task()})
        elif name == "end_task":
            emit({"tool": name, **await env.end_task()})
        else:
            emit({"tool": name, "ok": False, "error": f"unknown tool {name!r}"})
    return results


# ~93% of Qwen3.8-27B's real 262,144-token native context, leaving headroom
# below where generation quality degrades (see STUCK_NOTE).
HISTORY_BLOCK_MAX_TOKENS = 245_000


class HistoryBlockState:
    """Mutable holder for bootstrap_generate's persistent cache block --
    passed by reference so a plain function can reassign `.block` and have
    later calls see it."""

    def __init__(self) -> None:
        self.block: Optional["CacheBlock"] = None


async def bootstrap_generate(
    llm: "AsyncLLM",
    prompt: str,
    max_new_tokens: int = 131_072,
    on_token: Optional[HookFn] = None,
    history: Optional[HistoryBlockState] = None,
    reuse_prompt: Optional[str] = None,
    step: Optional[int] = None,
) -> str:
    """Recover with a fresh, correctly framed chat turn and temporary cache.

    Accept the legacy history argument to safely release any old recovery cache;
    failed completions are never used as the prefix of another recovery attempt.
    """
    # Recovery must not append a new request to the failed assistant's cache:
    # that repeatedly produced immediate EOS instead of a new response.
    from generation_prompt import revision_prompt, revision_completion
    if history is not None and history.block is not None:
        await llm.free_block(history.block)
        history.block = None
    owns_block, reused = True, False
    text = revision_prompt(llm, prompt)
    block = await llm.create_block()

    input_ids = llm.tokenizer(text, return_tensors="pt", add_special_tokens=False).input_ids
    ids = eos_ids(llm)
    try:
        new_token_id = await llm.sample(await llm(input_ids, cache_view=[block]))
        tokens: list[int] = []
        for _ in range(max_new_tokens):
            if on_token is not None:
                on_token(llm.tokenizer.decode(new_token_id))
            tokens.append(int(new_token_id))
            if int(new_token_id) in ids:
                stop_reason = "eos"
                break
            new_token_id = await llm.sample(await llm(new_token_id.view(1), cache_view=[block]))
        else:
            stop_reason = "budget-exhausted"
        logger.info(
            "bootstrap_generate step=%s stop=%s tokens=%d/%d block=%s(num_tokens=%d)",
            step, stop_reason, len(tokens), max_new_tokens,
            "reused" if reused else "fresh", block.num_tokens)
        return revision_completion(text, llm.tokenizer.decode(tokens, skip_special_tokens=False))
    finally:
        if owns_block:
            await llm.free_block(block)


class SelfEvolvingAgent:
    def __init__(self, env: SelfEditEnv, hooks: Optional[dict[str, HookFn]] = None) -> None:
        self.env = env
        self.hooks = hooks or {}
        # Keeps a caller's hang-watchdog heartbeat alive during long
        # start_task()/restart_task() calls, at both episode and step
        # granularity (see SelfEditEnv.task_env/on_episode_start).
        self.env.on_episode_start = partial(self._call_hook, "on_episode_start")
        self.env.on_step = partial(self._call_hook, "on_episode_start")
        # Optional replay recording (tasks/runner.py) -- no-op if unregistered.
        self.env.on_frame = partial(self._call_hook, "on_frame")
        self.env.on_episode_end = partial(self._call_hook, "on_episode_end")
        # Stuck-completion-loop detection (see STUCK_NOTE / run_step).
        self._last_completion: Optional[str] = None
        # Persistent cache block for the fallback path only (see
        # bootstrap_generate/HistoryBlockState) -- self-authored generate()
        # rounds are a black box the harness can't instrument.
        self._history = HistoryBlockState()
        self._step = 0
        # Best avg_reward seen this run, independent of which round's result
        # ended up in last_result["task"] -- surfaced read-only in
        # build_env_turn so the agent can tell regression from noise.
        self._best_score: Optional[float] = None
        self._best_round: Optional[int] = None

    def _call_hook(self, name: str, *args: Any) -> None:
        hook = self.hooks.get(name)
        if hook is not None:
            hook(*args)

    def initial_last_result(self, source: str) -> Optional[dict[str, Any]]:
        if self.env.load_error is not None:
            return {"tool_results": [], "source": source, "error": self.env.load_error, "fatal": True}
        return None

    async def run_step(
        self, source: str, last_result: Optional[dict[str, Any]], max_new_tokens: int = 131_072
    ) -> dict[str, Any]:
        """Generate exactly one round of thinking + tool calls against the
        live, persistent Engine instance. Self-contained -- callable once
        per process or in a loop (see run())."""
        self._step += 1
        round_start = time.monotonic()
        prompt_text = self.env.prompt.system_prompt if self.env.prompt is not None else None
        if prompt_text is None:
            prompt_text = FALLBACK_PROMPT + (self.env.prompt_load_error or "unknown error")
        task_status = None
        name = getattr(self.env.task_env, "name", None)
        if name:
            task_status = f"Current task env: {name}."
            # Any task env may expose a `doc` string (see tasks/ttft_env.py)
            # so task-specific steering lives there, not as branching here.
            doc = getattr(self.env.task_env, "doc", None)
            if doc:
                task_status += "\n" + doc
        best_so_far = (self._best_score, self._best_round) if self._best_score is not None else None
        prompt = build_prompt(source, last_result, prompt_text, task_status, max_new_tokens, best_so_far)
        self._call_hook("on_thought_start")
        try:
            # Fall back to bootstrap_generate() not just when generate is
            # uncallable, but also right after a crash or repeated completion
            # (STUCK_NOTE) -- otherwise a broken self-authored generate()
            # keeps re-selecting itself with no working "brain" left to fix it.
            engine_generate = getattr(self.env.engine, "generate", None)
            use_fallback = not callable(engine_generate) or bool(
                last_result and (last_result.get("crash") or last_result.get("repeated") or last_result.get("empty_completion")))
            generate = (
                partial(
                    bootstrap_generate, self.env.llm, history=self._history,
                    reuse_prompt=build_env_turn(last_result, task_status, max_new_tokens, best_so_far)
                    if self._history.block else None,
                    step=self._step)
                if use_fallback else engine_generate)
            completion = await generate(
                prompt, max_new_tokens=max_new_tokens,
                on_token=lambda token: self._call_hook("on_thought_token", token))
            if not isinstance(completion, str):
                # A non-str return (e.g. missing `return`) used to escape
                # this try block and crash the whole process downstream in
                # truncate_runaway(). Raise here to route it through the
                # same crash-recovery path as an exception in generate().
                raise TypeError(f"generate() must return a str, got {type(completion).__name__!r}: {completion!r}")
        except Exception:
            tb = traceback.format_exc()
            logger.exception("generation failed on current engine.py")
            result = {"tool_results": [], "source": source, "crash": tb, "fatal": False}
            result["round_delay_s"] = time.monotonic() - round_start
            self._call_hook("on_step_result", result)
            return result
        # Re-tokenized length vs. budget is a heuristic proxy for "hit the
        # token cap instead of stopping via EOS" -- the real stop reason is
        # invisible for a self-authored black-box generate().
        approx_tokens = len(self.env.llm.tokenizer(completion, add_special_tokens=False).input_ids)
        near_budget = approx_tokens >= max_new_tokens * 0.95
        if not use_fallback:
            if near_budget:
                logger.warning(
                    "self-authored generate() (step %d): completion ~%d tokens (cap %d) -- may have "
                    "been cut off by the token budget rather than stopping via EOS (heuristic: "
                    "re-tokenized output length, not the model's own decode-loop signal)",
                    self._step, approx_tokens, max_new_tokens)
            else:
                logger.info(
                    "self-authored generate() (step %d): completion ~%d tokens (cap %d) -- well under "
                    "the cap, likely stopped via EOS/natural completion (heuristic)",
                    self._step, approx_tokens, max_new_tokens)
        elif near_budget:
            logger.warning(
                "fallback bootstrap_generate() (step %d): completion ~%d tokens (cap %d) -- likely "
                "exhausted its token budget without reaching EOS",
                self._step, approx_tokens, max_new_tokens)
        raw_completion = completion
        completion = truncate_runaway(completion)
        if len(completion) != len(raw_completion):
            logger.warning(
                "truncated a runaway completion: %d -> %d chars (cut before %r)",
                len(raw_completion), len(completion), raw_completion[len(completion):len(completion) + 24])
        self._call_hook("on_completion", completion)

        # A completion identical to the last isn't caught by
        # MAX_CONSECUTIVE_IDENTICAL_CALLS (which only guards repeated tool
        # calls) -- detect it so the next round gets STUCK_NOTE + fallback.
        repeated = self._last_completion is not None and completion == self._last_completion
        self._last_completion = completion
        if repeated:
            logger.warning(
                "completion identical to the previous round's (%d chars) -- likely stuck; "
                "forcing safe fallback generation next round", len(completion))

        result: dict[str, Any] = {
            "tool_results": [], "source": self.env.screen, "fatal": False, "repeated": repeated,
            "near_budget": near_budget, "empty_completion": not strip_think(completion).strip()}

        def on_result(r: dict[str, Any]) -> None:
            # Fires as each tool call finishes, not after the round returns
            # -- see apply_tool_calls' on_result docstring.
            self._call_hook("on_tool_result", r)
            if r.get("tool") in ("start_task", "restart_task") and r.get("ok") and r.get("result") is not None:
                result["task"] = r["result"]
                self._call_hook("on_task_result", r["result"])

        result["tool_results"] = await apply_tool_calls(self.env, completion, on_result=on_result)
        result["round_delay_s"] = time.monotonic() - round_start
        result["invalid_reason"] = invalid_reason(result)
        if result["invalid_reason"] is None:
            reward = result["task"]["avg_reward"]
            if self._best_score is None or reward > self._best_score:
                self._best_score, self._best_round = reward, self._step
        self._call_hook("on_step_result", result)
        return result

    async def run(
        self, max_steps: int = 10, max_new_tokens: int = 131_072,
        target_valid_steps: Optional[int] = None, max_attempts: Optional[int] = None,
    ) -> None:
        """Evolve engine.py within this one process, so the live Engine
        instance persists across steps. Task evaluation is entirely
        agent-triggered via start_task/restart_task/end_task.

        With target_valid_steps set, only fresh, error-free evaluations that
        call LLM.forward() and compile successfully count -- runs until that many
        valid rounds complete, capped at max_attempts total as a safety
        valve. With it None (default), runs exactly max_steps regardless."""
        source = self.env.reset()
        self._call_hook("on_env_reset", source)
        last_result = self.initial_last_result(source)

        total_cap = (max_attempts or 2 * target_valid_steps) if target_valid_steps is not None else max_steps
        valid_steps = 0
        step = 0
        while step < total_cap and (target_valid_steps is None or valid_steps < target_valid_steps):
            logger.info(
                "step %d/%d (valid %d/%s): generating next round",
                step + 1, total_cap, valid_steps,
                target_valid_steps if target_valid_steps is not None else "-")
            last_result = await self.run_step(source, last_result, max_new_tokens=max_new_tokens)
            source = last_result.get("source", source)
            step += 1
            reason = invalid_reason(last_result)
            if reason is None:
                valid_steps += 1
            else:
                logger.warning("Round excluded: %s", reason)
        self.valid_steps = valid_steps
        if target_valid_steps is not None and valid_steps < target_valid_steps:
            logger.warning(
                "gave up after %d attempts (cap %d) with only %d/%d valid rounds",
                step, total_cap, valid_steps, target_valid_steps)
