from __future__ import annotations

import logging
import re
import time
import traceback
from functools import partial
from typing import TYPE_CHECKING, Any, Callable, Optional

from self_edit_env import SelfEditEnv

if TYPE_CHECKING:
    from minisgl.llm import AsyncLLM
    from minisgl.shared_cache.shared_block import CacheBlock

logger = logging.getLogger(__name__)

HookFn = Callable[..., None]

FATAL_NOTE = """
Your current engine.py does not even compile/construct -- it is completely broken, so this \
thought is being generated by a fixed fallback path instead of your own `generate` method. Call \
`write_engine` with a fixed version and then `reload_engine_methods` to bring yourself back to \
life. The failure was:
"""

STUCK_NOTE = """
Your last round's completion came out byte-for-byte identical to the round before it -- you are \
stuck reproducing the same content instead of reasoning fresh (seen live: a persistent cache block \
kept alive across every call to `generate`, including the once-per-episode calls `act` makes during \
`start_task`/`restart_task`, can grow large enough that continuing from it just regurgitates \
whatever is already sitting inside it). This round is being generated by the safe fallback path \
instead of your own `generate` so you have a clean context to look at and decide what to do. If \
`engine.py` holds a persistent block on `self` that is never freed, its unbounded growth across \
*all* of those calls -- not just successive rounds of you rewriting yourself -- is the first thing \
worth checking.
"""

FALLBACK_PROMPT = """You are an inference engine that thinks by executing the Python code in \
`mutable/engine.py` and is instructed by `mutable/prompt.py`. Your `prompt.py` currently fails \
to compile/construct, or its `Prompting` instance has no string `system_prompt` attribute, so \
this minimal fallback is being used instead of your real instructions.

Call `write_prompt` with a fixed `prompt.py` (it must define a top-level class `Prompting` with \
`def __init__(self, llm)` that sets `self.system_prompt = "..."`) and then `reload_prompt` to \
restore your real instructions. Use this exact syntax:

<use_tool name="write_prompt">
```python
class Prompting:
    def __init__(self, llm):
        self.llm = llm
        self.system_prompt = \"\"\"<the full new prompt text>\"\"\"
```
</use_tool>
<use_tool name="reload_prompt"></use_tool>

The failure was:
"""

_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL)
_UNCLOSED_THINK_RE = re.compile(r"<think>.*", re.DOTALL)
_TOOL_CALL_RE = re.compile(r'<use_tool\s+name="(\w+)"\s*>(.*?)</use_tool>', re.DOTALL)

# A legitimate single-round completion never contains these -- each round
# starts a fresh generation, so if either shows up mid-completion it means
# decoding ran past the model's real turn boundary (e.g. because the
# decode loop only checked one eos id while the model's generation_config
# lists several) and kept going into leaked/regurgitated context. Cutting
# here before tool-call parsing stops that leaked text -- which can itself
# contain this very prompt's own illustrative <use_tool> examples -- from
# ever being treated as real tool calls.
_RUNAWAY_MARKERS = ("<|endoftext|>", "<|im_start|>")


def truncate_runaway(text: str) -> str:
    cut = min((text.find(m) for m in _RUNAWAY_MARKERS if m in text), default=len(text))
    return text[:cut]


def eos_ids(llm: "AsyncLLM") -> set[int]:
    """The tokenizer's own eos_token_id is often just one id (e.g. Qwen3.5's
    is <|im_end|>), but the model's real generation_config.eos_token_id can
    list several (Qwen3.5's also includes <|endoftext|>) -- stopping on only
    the tokenizer's single id misses real stop signals and lets decoding run
    away. Union both sources."""
    ids = {llm.tokenizer.eos_token_id}
    gen_cfg = getattr(getattr(getattr(llm, "engine", None), "config", None), "generation_config", None)
    gen_eos = getattr(gen_cfg, "eos_token_id", None)
    if isinstance(gen_eos, int):
        ids.add(gen_eos)
    elif isinstance(gen_eos, (list, tuple, set)):
        ids.update(gen_eos)
    return ids


def strip_think(text: str) -> str:
    text = _THINK_RE.sub("", text)
    text = _UNCLOSED_THINK_RE.sub("", text)
    return text


def extract_code(text: str) -> Optional[str]:
    if "```python" in text:
        return text.split("```python", 1)[1].split("```", 1)[0].strip()
    if "```" in text:
        return text.split("```", 1)[1].split("```", 1)[0].strip()
    return None


def build_env_turn(
    last_result: Optional[dict[str, Any]], task_status: Optional[str] = None,
    max_new_tokens: Optional[int] = None,
) -> str:
    """The last-round-outcome part of a round's prompt -- tool results, crash
    text, task score/error, task status -- with no engine.py source dump and
    no system-prompt preamble. Used as build_prompt()'s tail for a normal
    full round, and standalone as the compact per-round delta fed into a
    *reused* bootstrap_generate history block (see HistoryBlockState):
    re-prefilling the whole source+preamble into that block every call would
    burn its token budget in a handful of rounds for no benefit, since the
    model's own prior reasoning is already sitting in that block's real KV
    from when it was generated -- this never re-quotes it as text."""
    parts = []
    if last_result is not None:
        if last_result.get("fatal"):
            parts.append(FATAL_NOTE + last_result["error"])
        elif last_result.get("crash"):
            parts.append("\nYour last generation crashed before any tool calls could run:\n"
                          + last_result["crash"])
        else:
            tool_results = last_result.get("tool_results") or []
            if not tool_results:
                parts.append("\nYour last round made no <use_tool> calls -- nothing changed.")
            else:
                lines = []
                for r in tool_results:
                    status = "OK" if r.get("ok") else "ERROR"
                    line = f"- {r.get('tool')}: {status}"
                    if not r.get("ok"):
                        line += f"\n  {r.get('error')}"
                    elif r.get("changed"):
                        line += f" (changed: {', '.join(r['changed'])})"
                    lines.append(line)
                parts.append("\nYour last round's tool calls:\n" + "\n".join(lines))
        if last_result.get("repeated"):
            parts.append(STUCK_NOTE)
        task = last_result.get("task")
        if task is not None:
            parts.append(f"\nLatest task score on `{task['env']}`: avg_reward={task['avg_reward']:.3f} "
                          f"over {len(task['episodes'])} episode(s).")
            # avg_reward alone doesn't say *why* a score is low -- an episode
            # that crashed inside act() (see tasks/runner.py's per-episode
            # try/except) scores 0 with its traceback recorded in that
            # episode's info, but that traceback was never actually shown
            # here before, so a bug like this could recur silently for many
            # rounds with nothing but a flat 0.0 to go on. Surface the first
            # one so it's visible right where the score is.
            error = next(
                (e["info"]["error"] for e in task["episodes"]
                 if isinstance(e.get("info"), dict) and e["info"].get("error")), None)
            if error:
                parts.append(
                    "An episode failed with this traceback -- fix whatever it points to in "
                    f"engine.py:\n{error}")
            # Per-episode avg_act_latency_s (see tasks/doom_env.py) is a running
            # mean over that episode's steps -- mean those into one figure so a
            # slow act() shows up here, not just in the abstract.
            latencies = [
                e["info"]["avg_act_latency_s"] for e in task["episodes"]
                if isinstance(e.get("info"), dict) and e["info"].get("avg_act_latency_s") is not None
            ]
            if latencies:
                parts.append(
                    f"Avg act() latency this task run: {sum(latencies) / len(latencies) * 1000:.0f}ms "
                    "(mean wall-clock time between receiving an observation and returning an action).")
    if task_status is not None:
        parts.append("\n" + task_status)
    if max_new_tokens is not None:
        parts.append(f"\nThis round's generation is capped at max_new_tokens={max_new_tokens}.")
    parts.append("\nWrite your next round (thinking, then <use_tool> calls):")
    return "\n".join(parts)


def build_prompt(
    source: str, last_result: Optional[dict[str, Any]], prompt: str,
    task_status: Optional[str] = None, max_new_tokens: Optional[int] = None,
) -> str:
    parts = [prompt, "\nCurrent engine.py:\n```python\n" + source + "\n```",
              build_env_turn(last_result, task_status, max_new_tokens)]
    return "\n".join(parts)


# Hard ceilings on tool-call execution per round, enforced here in agent.py
# (harness code the agent can never rewrite -- only mutable/engine.py and
# mutable/prompt.py are agent-editable, via write_engine/write_prompt). Seen
# live: a sampling config with no repetition penalty can get the model stuck
# emitting the same short <use_tool> tag dozens/hundreds of times in one
# completion. The repeated tags themselves cost nothing (the whole completion
# is already generated by the time this function runs) -- the real cost is
# *executing* each one, which for start_task/restart_task means running full
# task episodes (minutes of GPU time apiece). Capping execution count here
# bounds the wall-clock/GPU damage regardless of how degenerate the text is.
MAX_TOOL_CALLS_PER_ROUND = 8
MAX_CONSECUTIVE_IDENTICAL_CALLS = 3


async def apply_tool_calls(
    env: SelfEditEnv, completion: str, on_result: Optional[HookFn] = None,
) -> list[dict[str, Any]]:
    """`on_result`, if given, fires the moment each individual tool call
    finishes -- not just once at the very end. A single slow call (e.g.
    start_task running real episodes) used to leave the structured
    tool_results.log/task_results.log hooks silent until the *whole* round's
    loop returned, even though main.log kept showing live progress from
    self_edit_env's own logger calls in the meantime -- making a long-running
    but healthy round look identical to a stall in the structured logs."""
    text = strip_think(completion)
    results: list[dict[str, Any]] = []
    prev_call: Optional[tuple[str, str]] = None
    consecutive = 0

    def emit(result: dict[str, Any]) -> None:
        results.append(result)
        if on_result is not None:
            on_result(result)

    for name, inner in _TOOL_CALL_RE.findall(text):
        if len(results) >= MAX_TOOL_CALLS_PER_ROUND:
            emit({"tool": name, "ok": False,
                  "error": f"round tool-call budget exceeded ({MAX_TOOL_CALLS_PER_ROUND} max "
                           "calls per round) -- remaining calls in this round were skipped"})
            break
        call = (name, inner)
        consecutive = consecutive + 1 if call == prev_call else 1
        prev_call = call
        if consecutive > MAX_CONSECUTIVE_IDENTICAL_CALLS:
            emit({"tool": name, "ok": False,
                  "error": f"stopped after {MAX_CONSECUTIVE_IDENTICAL_CALLS} identical "
                           f"consecutive calls to {name!r} -- this looks like a generation "
                           "loop, not deliberate repetition; remaining calls in this round "
                           "were skipped"})
            break
        if name == "write_engine":
            source = extract_code(inner)
            if source is None:
                emit({"tool": name, "ok": False,
                      "error": "no code block found inside write_engine call"})
                continue
            emit({"tool": name, **env.write_engine(source)})
        elif name == "reload_engine_methods":
            emit({"tool": name, **env.reload_engine_methods()})
        elif name == "write_prompt":
            source = extract_code(inner)
            if source is None:
                emit({"tool": name, "ok": False,
                      "error": "no code block found inside write_prompt call"})
                continue
            emit({"tool": name, **env.write_prompt(source)})
        elif name == "reload_prompt":
            emit({"tool": name, **env.reload_prompt()})
        elif name == "start_task":
            emit({"tool": name, **await env.start_task()})
        elif name == "restart_task":
            emit({"tool": name, **await env.restart_task()})
        elif name == "end_task":
            emit({"tool": name, **await env.end_task()})
        else:
            emit({"tool": name, "ok": False, "error": f"unknown tool {name!r}"})
    return results


# ~93% of the model's real 262,144-token native context (Qwen3.8-27B's
# max_position_embeddings, confirmed from its config.json -- not the 128k
# figure this comment used to say), leaving real headroom below the point
# generation quality silently degrades (see STUCK_NOTE) -- checked as
# existing-block tokens + this round's new prompt + this round's decode
# budget, since the about-to-be-prefilled prompt becomes part of the block
# going forward too.
HISTORY_BLOCK_MAX_TOKENS = 245_000


class HistoryBlockState:
    """Mutable holder for bootstrap_generate's persistent cache block, owned
    by SelfEvolvingAgent and threaded through via partial(...). A plain
    Optional[CacheBlock] attribute on SelfEvolvingAgent wouldn't let
    bootstrap_generate (a free function bound only to llm) reassign it in a
    way later calls would see -- this object is passed by reference so
    `history.block = ...` reassignment is visible on the next call."""

    def __init__(self) -> None:
        self.block: Optional["CacheBlock"] = None


async def bootstrap_generate(
    llm: "AsyncLLM",
    prompt: str,
    max_new_tokens: int = 131_072,
    on_token: Optional[HookFn] = None,
    history: Optional[HistoryBlockState] = None,
    reuse_prompt: Optional[str] = None,
    step: Optional[int] = None,
) -> str:
    """Fixed fallback mirroring the seed engine.py's own generate(), used
    whenever the current engine.py is too broken to construct, or the
    previous round crashed/repeated -- there is no other way to ask the agent
    for a fix in those cases.

    With `history` given, the underlying cache block is kept alive and grown
    across calls instead of being freed every time (mirroring the
    keep-a-block-alive idiom already taught to the agent itself in
    mutable/prompt.py), so this fallback path's own rounds carry real
    continuity: each reused call only prefills `reuse_prompt` (the compact
    last-round-outcome delta, see build_env_turn) against the existing block
    rather than the full `prompt`, since the model's prior reasoning is
    already in that block's real KV. Growth is capped by
    HISTORY_BLOCK_MAX_TOKENS -- crossing it frees the block and the next call
    starts fresh with the full `prompt`, the same regurgitation risk
    STUCK_NOTE documents for an unboundedly-growing self-authored block."""
    owns_block = history is None
    reused = False
    if history is not None and history.block is not None:
        candidate_text = reuse_prompt if reuse_prompt is not None else prompt
        candidate_ids = llm.tokenizer(
            candidate_text, return_tensors="pt", add_special_tokens=False).input_ids
        projected = history.block.num_tokens + candidate_ids.shape[-1] + max_new_tokens
        if projected <= HISTORY_BLOCK_MAX_TOKENS:
            reused = True
            text = candidate_text
        else:
            logger.warning(
                "history block reset: existing=%d + new=%d + budget=%d = %d tokens would exceed "
                "%d -- freeing, this call starts fresh (step=%s)",
                history.block.num_tokens, candidate_ids.shape[-1], max_new_tokens, projected,
                HISTORY_BLOCK_MAX_TOKENS, step)
            await llm.free_block(history.block)
            history.block = None
    if history is not None and history.block is None:
        history.block = await llm.create_block()
    if not reused:
        text = prompt
    block = history.block if history is not None else await llm.create_block()

    input_ids = llm.tokenizer(text, return_tensors="pt", add_special_tokens=False).input_ids
    ids = eos_ids(llm)
    try:
        new_token_id = await llm.sample(await llm(input_ids, cache_view=[block]))
        tokens: list[int] = []
        for _ in range(max_new_tokens):
            if on_token is not None:
                on_token(llm.tokenizer.decode(new_token_id))
            tokens.append(int(new_token_id))
            if int(new_token_id) in ids:
                stop_reason = "eos"
                break
            new_token_id = await llm.sample(await llm(new_token_id.view(1), cache_view=[block]))
        else:
            stop_reason = "budget-exhausted"
        logger.info(
            "bootstrap_generate step=%s stop=%s tokens=%d/%d block=%s(num_tokens=%d)",
            step, stop_reason, len(tokens), max_new_tokens,
            "reused" if reused else "fresh", block.num_tokens)
        return llm.tokenizer.decode(tokens, skip_special_tokens=True)
    finally:
        if owns_block:
            await llm.free_block(block)


class SelfEvolvingAgent:
    def __init__(self, env: SelfEditEnv, hooks: Optional[dict[str, HookFn]] = None) -> None:
        self.env = env
        self.hooks = hooks or {}
        # So a long start_task()/restart_task() run still touches a caller's
        # hang-watchdog heartbeat even though it's no longer driven from
        # run()'s loop body -- see SelfEditEnv.task_env/on_episode_start.
        self.env.on_episode_start = partial(self._call_hook, "on_episode_start")
        # Same reasoning, but per-step rather than per-episode: a real
        # multi-step game episode (see tasks/doom_env.py) can take longer
        # than the watchdog's timeout on its own, well before the next
        # on_episode_start heartbeat would fire.
        self.env.on_step = partial(self._call_hook, "on_episode_start")
        # Harness-only bookkeeping (never exposed to the agent) for detecting
        # a stuck completion loop -- see STUCK_NOTE / run_step below.
        self._last_completion: Optional[str] = None
        # Persistent cache block for the fallback generation path only (see
        # bootstrap_generate/HistoryBlockState) -- self-authored
        # engine.generate() rounds are a black box the harness can't
        # instrument, so this never sees those rounds' reasoning.
        self._history = HistoryBlockState()
        self._step = 0

    def _call_hook(self, name: str, *args: Any) -> None:
        hook = self.hooks.get(name)
        if hook is not None:
            hook(*args)

    def initial_last_result(self, source: str) -> Optional[dict[str, Any]]:
        if self.env.load_error is not None:
            return {"tool_results": [], "source": source, "error": self.env.load_error, "fatal": True}
        return None

    async def run_step(
        self, source: str, last_result: Optional[dict[str, Any]], max_new_tokens: int = 131_072
    ) -> dict[str, Any]:
        """Generate exactly one round of thinking + tool calls against the
        live, persistent Engine instance. Self-contained: fine to call once
        per process (relaunch loop) or in a for-loop within one process
        (see run())."""
        self._step += 1
        round_start = time.monotonic()
        prompt_text = self.env.prompt.system_prompt if self.env.prompt is not None else None
        if prompt_text is None:
            prompt_text = FALLBACK_PROMPT + (self.env.prompt_load_error or "unknown error")
        task_status = None
        name = getattr(self.env.task_env, "name", None)
        if name:
            task_status = f"Current task env: {name}."
            # Generic hook: any task env may expose a `doc` string explaining
            # how it specifically scores act() (see tasks/ttft_env.py) --
            # surfaced here so task-specific steering lives in the task env
            # itself, not as more agent.py/self_edit_env.py branching per task.
            doc = getattr(self.env.task_env, "doc", None)
            if doc:
                task_status += "\n" + doc
        prompt = build_prompt(source, last_result, prompt_text, task_status, max_new_tokens)
        self._call_hook("on_thought_start")
        try:
            # Fall back to the safe bootstrap generate() not only when the
            # current engine.py's generate is uncallable, but also right
            # after it crashed last round -- otherwise a self-authored bug
            # that only manifests once methods are patched onto the live
            # instance (e.g. a new method assuming __init__-set state that
            # never ran, see reload_engine_methods) re-selects the same
            # broken method forever, in a crash loop with no working "brain"
            # left to ever read the traceback and fix it.
            # Same reasoning applies to a round that came out identical to the
            # one before it (see STUCK_NOTE): re-selecting the same
            # self-authored generate() would just reproduce the same stuck
            # state again, so give it one clean round on the fallback path
            # instead.
            engine_generate = getattr(self.env.engine, "generate", None)
            use_fallback = not callable(engine_generate) or bool(
                last_result and (last_result.get("crash") or last_result.get("repeated")))
            generate = (
                partial(
                    bootstrap_generate, self.env.llm, history=self._history,
                    reuse_prompt=build_env_turn(last_result, task_status, max_new_tokens)
                    if self._history.block else None,
                    step=self._step)
                if use_fallback else engine_generate)
            completion = await generate(
                prompt, max_new_tokens=max_new_tokens,
                on_token=lambda token: self._call_hook("on_thought_token", token))
            if not isinstance(completion, str):
                # A self-authored generate() that returns None/non-str (e.g. a
                # missing return statement) used to escape this try block
                # entirely -- truncate_runaway() below would then blow up on
                # a plain str method call and crash the whole persistent
                # process, losing every step of progress. Raising here routes
                # it through the same crash-recovery path as an exception
                # inside generate() itself: fed back next round, fallback
                # generation takes over so the agent can see and fix it.
                raise TypeError(f"generate() must return a str, got {type(completion).__name__!r}: {completion!r}")
        except Exception:
            tb = traceback.format_exc()
            logger.exception("generation failed on current engine.py")
            result = {"tool_results": [], "source": source, "crash": tb, "fatal": False}
            result["round_delay_s"] = time.monotonic() - round_start
            self._call_hook("on_step_result", result)
            return result
        if not use_fallback:
            # engine.generate() is the agent's own black-box decode loop --
            # the harness can't see whether it stopped via EOS or got cut off
            # by max_new_tokens, so this re-tokenizes the returned string and
            # compares its length to the budget as a heuristic proxy only.
            approx_tokens = len(self.env.llm.tokenizer(completion, add_special_tokens=False).input_ids)
            if approx_tokens >= max_new_tokens * 0.95:
                logger.warning(
                    "self-authored generate() (step %d): completion ~%d tokens (cap %d) -- may have "
                    "been cut off by the token budget rather than stopping via EOS (heuristic: "
                    "re-tokenized output length, not the model's own decode-loop signal)",
                    self._step, approx_tokens, max_new_tokens)
            else:
                logger.info(
                    "self-authored generate() (step %d): completion ~%d tokens (cap %d) -- well under "
                    "the cap, likely stopped via EOS/natural completion (heuristic)",
                    self._step, approx_tokens, max_new_tokens)
        raw_completion = completion
        completion = truncate_runaway(completion)
        if len(completion) != len(raw_completion):
            logger.warning(
                "truncated a runaway completion: %d -> %d chars (cut before %r)",
                len(raw_completion), len(completion), raw_completion[len(completion):len(completion) + 24])
        self._call_hook("on_completion", completion)

        # A completion byte-for-byte identical to the previous round's is not
        # caught by MAX_CONSECUTIVE_IDENTICAL_CALLS (that only guards repeated
        # *tool calls* within/across rounds) -- a round that makes zero tool
        # calls can still repeat forever with no backstop at all. Detect it
        # here so the next round gets STUCK_NOTE and a clean fallback
        # generation instead of silently repeating.
        repeated = self._last_completion is not None and completion == self._last_completion
        self._last_completion = completion
        if repeated:
            logger.warning(
                "completion identical to the previous round's (%d chars) -- likely stuck; "
                "forcing safe fallback generation next round", len(completion))

        result: dict[str, Any] = {
            "tool_results": [], "source": self.env.screen, "fatal": False, "repeated": repeated}

        def on_result(r: dict[str, Any]) -> None:
            # Fires the instant each tool call finishes, not after the whole
            # round's loop returns -- so a slow single call (e.g. start_task
            # running real episodes) still shows up in tool_results.log/
            # task_results.log as it happens, instead of those structured
            # logs going silent for the entire round while main.log (fed by
            # self_edit_env's own logger calls) keeps moving.
            self._call_hook("on_tool_result", r)
            if r.get("tool") in ("start_task", "restart_task") and r.get("ok") and r.get("result") is not None:
                result["task"] = r["result"]
                self._call_hook("on_task_result", r["result"])

        result["tool_results"] = await apply_tool_calls(self.env, completion, on_result=on_result)
        result["round_delay_s"] = time.monotonic() - round_start
        self._call_hook("on_step_result", result)
        return result

    async def run(self, max_steps: int = 10, max_new_tokens: int = 131_072) -> None:
        """Evolve engine.py for max_steps within this one process, so the
        live Engine instance (and anything it holds, e.g. cache blocks)
        persists across every step. Task evaluation (if env.task_env is
        set) is entirely agent-triggered via the start_task/restart_task/
        end_task tools -- there is no external cadence here."""
        source = self.env.reset()
        self._call_hook("on_env_reset", source)
        last_result = self.initial_last_result(source)

        for step in range(max_steps):
            logger.info("step %d/%d: generating next round", step + 1, max_steps)
            last_result = await self.run_step(source, last_result, max_new_tokens=max_new_tokens)
            source = last_result.get("source", source)
